### ISSUE TITLE
Provide installation instructions

### ISSUE THREAD

**Issue by jacobjj** [BrandNewLifeJackie26/productRight#5]
Providing package dependencies could improve the reproducibility of your codebase. Add `requirements.txt` to your repo.

**Comment by BrandNewLifeJackie26** [comment]
We are actually dividing project into front-end and back-end. So we have dependency file inside the subdirectories:
- back-end requirement: [`requirements.txt`](https://github.com/BrandNewLifeJackie26/productRight/blob/main/flask-app/requirements.txt)
- front-end dependencies: [`package.json`](https://github.com/BrandNewLifeJackie26/productRight/blob/main/react-app/package.json)

But yes, maybe I should put them in the README file.

**Comment by jacobjj** [comment]
maybe worth mentioning it in the `README.md`
