### ISSUE TITLE
Link to test data

### ISSUE THREAD

**Issue by jacobjj** [BrandNewLifeJackie26/productRight#6]
Provide the dataset used for testing.

**Comment by nileshpd1211** [comment]
We have divided the testing part of our project in two parts: Testing for recommendation engine (all functions used for the recommendation engine is in /test/recommendation_engine.py) and Testing for analytical engine (all functions used for the recommendation engine is in /test/analysis_engine.py).

Regarding test datasets:
1. We use the dataset a subset of main_TopTranNv.csv (/test/main_TopTranNv.csv) for testing functions of the analytical engine
2. We use a dummy created pandas dataframe (defined in /test/recommendation_engine.py) to test the recommendation engine

The testing functions can be found in /test/test_overall.py used to generate the individual and overall code coverage report.

**Comment by jacobjj** [comment]
I ran the test from the home folder; hence, the script could not find the data file. But running pytest in the test folder seems to work.
